import React, { useEffect, useRef, useState } from 'react';
import { CheckCheck, Clock3, MessageCircle, RefreshCw, Search, Send, User as UserRound, X } from 'lucide-react';
import { formatCurrency, formatDateTime } from '../../utils/formatters';
import { crmJson, crmRequest, crmStatusLabel, crmStatusTone } from './crmApi';

function MessageBubble({ message }) {
  const outbound = message.direction === 'OUTBOUND';
  return <article className={`crm-message ${outbound ? 'outbound' : 'inbound'}`}><div>{message.text_body || (message.message_type === 'template' ? 'Plantilla de WhatsApp' : `[${message.message_type}]`)}</div><small>{formatDateTime(message.created_at)} {outbound && <><span>{message.status}</span>{['DELIVERED','READ'].includes(message.status) && <CheckCheck size={13} />}</>}</small></article>;
}

export default function CrmInbox({ revision, notify }) {
  const [conversations,setConversations]=useState([]); const [selected,setSelected]=useState(null); const [detail,setDetail]=useState(null); const [search,setSearch]=useState(''); const [status,setStatus]=useState(''); const [text,setText]=useState(''); const [templates,setTemplates]=useState([]); const [templateId,setTemplateId]=useState(''); const [sending,setSending]=useState(false); const bottomRef=useRef(null);
  const loadList=async()=>{try{const query=new URLSearchParams({limit:100,search,status});const data=await crmRequest(`/conversations?${query}`);setConversations(data.conversations);if(selected&&!data.conversations.some(item=>Number(item.id)===Number(selected)))setSelected(null);}catch(error){notify('error',error.message);}};
  const loadDetail=async(id=selected)=>{if(!id)return;try{const data=await crmRequest(`/conversations/${id}`);setDetail(data);await crmRequest(`/conversations/${id}/read`,crmJson('POST',{}));setTimeout(()=>bottomRef.current?.scrollIntoView({behavior:'smooth'}),30);}catch(error){notify('error',error.message);}};
  useEffect(()=>{const timer=setTimeout(loadList,220);return()=>clearTimeout(timer);},[search,status,revision]);
  useEffect(()=>{crmRequest('/templates').then(data=>setTemplates(data.templates.filter(item=>item.status==='APPROVED'))).catch(()=>{});},[]);
  useEffect(()=>{if(selected)loadDetail(selected);else setDetail(null);},[selected,revision]);
  const send=async()=>{if(!text.trim()&&!templateId)return;setSending(true);try{const template=templates.find(item=>String(item.id)===String(templateId));await crmRequest(`/conversations/${selected}/messages`,crmJson('POST',template?{template:{id:template.id,components:[]}}:{text},{'Idempotency-Key':crypto.randomUUID()}));setText('');setTemplateId('');notify('success','Mensaje agregado a la cola oficial.');await loadDetail();}catch(error){notify('error',error.message);}finally{setSending(false);}};
  const updateConversation=async(nextStatus,assignedUserId=detail?.conversation?.assigned_user_id??null)=>{try{await crmRequest(`/conversations/${selected}`,crmJson('PUT',{status:nextStatus,assigned_user_id:assignedUserId}));await loadList();await loadDetail();}catch(error){notify('error',error.message);}};
  return <section className={`crm-inbox ${selected?'show-detail':''}`}>
    <aside className="crm-inbox-list ds-card"><header><div><span className="ds-page-kicker">Bandeja omnicanal</span><h2>Conversaciones</h2></div><button className="ds-btn ds-btn-ghost ds-btn-sm" onClick={loadList}><RefreshCw size={16}/></button></header><div className="crm-inbox-filters"><label className="ds-search"><span className="ds-search-icon"><Search size={17}/></span><input className="ds-search-input" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Buscar contacto"/></label><select className="ds-select" value={status} onChange={event=>setStatus(event.target.value)}><option value="">Todas</option><option value="OPEN">Abiertas</option><option value="PENDING">Pendientes</option><option value="CLOSED">Cerradas</option></select></div><div className="crm-conversation-list">{conversations.length?conversations.map(item=><button key={item.id} className={Number(selected)===Number(item.id)?'active':''} onClick={()=>setSelected(item.id)}><span className="crm-conversation-avatar">{item.display_name?.[0]?.toUpperCase()||'?'}</span><div><strong>{item.display_name||item.normalized_phone}</strong><p>{item.last_message_text||`[${item.last_message_type||'sin mensajes'}]`}</p><small>{formatDateTime(item.last_message_at)}</small></div>{item.unread_count>0&&<b>{item.unread_count}</b>}</button>):<div className="ds-empty-state"><MessageCircle/><h3>Sin conversaciones</h3><p>Los mensajes entrantes aparecerán aquí en tiempo real.</p></div>}</div></aside>
    <main className="crm-chat ds-card">{detail?<><header className="crm-chat-header"><button className="crm-chat-back" onClick={()=>setSelected(null)}><X/></button><div className="crm-conversation-avatar">{detail.conversation.display_name?.[0]?.toUpperCase()||'?'}</div><div><strong>{detail.conversation.display_name||detail.conversation.normalized_phone}</strong><small>{detail.conversation.normalized_phone} · {crmStatusLabel(detail.conversation.contact_status)}</small></div><span className={`ds-badge ds-badge-${crmStatusTone(detail.conversation.contact_status)}`}>{crmStatusLabel(detail.conversation.contact_status)}</span><select className="ds-select crm-conversation-status" value={detail.conversation.status} onChange={event=>updateConversation(event.target.value)}><option value="OPEN">Abierta</option><option value="PENDING">Pendiente</option><option value="CLOSED">Cerrada</option></select></header><div className="crm-chat-context"><span><UserRound size={15}/>{detail.conversation.orders_count} pedidos</span><span><Clock3 size={15}/>{formatCurrency(detail.conversation.total_spent)} comprado</span></div><div className="crm-messages">{detail.messages.map(message=><MessageBubble key={message.id} message={message}/>) }<div ref={bottomRef}/></div><footer className="crm-composer"><div className="crm-template-row"><select className="ds-select" value={templateId} onChange={event=>setTemplateId(event.target.value)}><option value="">Mensaje libre (ventana de 24 h)</option>{templates.map(template=><option key={template.id} value={template.id}>{template.name} · {template.language}</option>)}</select></div>{!templateId&&<textarea className="ds-textarea" value={text} onChange={event=>setText(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();send();}}} placeholder="Escribe una respuesta…"/>}<button className="ds-btn ds-btn-primary" onClick={send} disabled={sending||(!text.trim()&&!templateId)}><Send size={18}/>{sending?'Enviando…':'Enviar'}</button></footer></>:<div className="ds-empty-state"><MessageCircle/><h3>Selecciona una conversación</h3><p>Consulta el historial completo y responde sin salir del ERP.</p></div>}</main>
  </section>;
}
